FEAT: define JSON schema for amplitude model format
RUB-EP1/amplitude-serialization pull request #30
Opened 2024-05-13 08:36 UTC by redeboer

Defined a JSON schema based on the example [`Lc2ppiK.json`](https://github.com/RUB-EP1/amplitude-serialization/blob/ecee71af8f77bc0360b3c5d8bc85592802652eb0/models/Lc2ppiK.json) while understanding the format. The model is directly evaluated in VSCode — give it a try, by messing up some of the values and hovering over the keys to see their descriptions.

Admittedly, JSON schema has less features than I thought. Particularly, I had hoped to build [`enum`](https://json-schema.org/understanding-json-schema/reference/enum)s for for instance the function names from the functions that are defined under `functions`. As far as I understand, that cannot be done dynamically with JSON schema. Still, there are some fancy things you can do, like validating whether spin definitions are valid.

2024-05-13 08:37 UTC, redeboer commented
@IlyaSegal maybe this schema is helpful for https://github.com/RUB-EP1/amplitude-serialization/issues/6?

2024-05-13 08:41 UTC, redeboer commented on .pre-commit-config.yaml
> +        exclude: ^models/HS3.*\.json$
See https://github.com/RUB-EP1/amplitude-serialization/pull/29#issuecomment-2106960482

2024-05-13 08:42 UTC, redeboer commented on .vscode/settings.json
>    }
The schema also works if the model is dumped to YAML!

2024-05-13 14:21 UTC, mmikhasenko commented
So much fun. Copilot can take use of it, and write parts of the file.

2024-05-13 14:22 UTC, redeboer commented
If it works with #6, we can merge it.

2024-05-13 14:26 UTC, mmikhasenko commented on schema.json
> +              }
not a key, but an element of the `functions` list, with a `name` field matching the `parametrization` specified here

2024-05-13 14:45 UTC, mmikhasenko requested changes
Nice! Do you know if `json` schemas can be nested? - i has been discussed at [HS3](https://github.com/hep-statistics-serialization-standard/hep-statistics-serialization-standard/issues/3) for long time

2024-05-13 14:45 UTC, mmikhasenko commented on schema.json
> +          ],
I'm not comfortable limiting this list. We should discuss it again, what are options
E.g. `BreitWignerWidthExpLikeBugg` is so specific to a particular single analysis.

2024-05-13 14:45 UTC, mmikhasenko commented on schema.json
> +          "description": "The quantum spin number of the particle, represented in string format",
spin quantum number

2024-05-13 14:45 UTC, mmikhasenko commented on schema.json
> +            "Recoupling with LS computes the value of the recoupling functions from Clebsch–Gordan coefficients. For spin-half particles, this recoupling scales with the parity factor, with f = (-1)^
> For spin-half particles, this recoupling scales with the parity factor, with f = (-1)^l."

not sure if it's needed here. Also, unclear what you mean and if it's only valid for spin-half

2024-05-13 14:45 UTC, mmikhasenko commented on schema.json
> +            "No recoupling. The factor is 1 for a pair of selected helicities and zero for other combinations. Easiest to implement with a Kronecker-Delta."
I'd remove the part, "Easiest to implement with a Kronecker-Delta."

2024-05-13 14:45 UTC, mmikhasenko commented on schema.json
> +        },
only for `parity couplings` not for LS. The `l` in `ls` defines something like this "parity factor" as `(-1)^l *P1 * P2`.

2024-05-13 14:45 UTC, mmikhasenko commented on schema.json
> +        },
remove. not needed for `ls`

2024-05-13 14:45 UTC, mmikhasenko commented on schema.json
> +        },
but for ls, one needs `l`::Number and `s`::Spin or both ::Spin

2024-05-13 15:00 UTC, redeboer commented
> Nice! Do you know if `json` schemas can be nested?

Do you mean [schema composition](https://json-schema.org/understanding-json-schema/reference/combining)? It's essentially already happening through the `definitions` key, you would then have to extract those definitions to a separate schema.

2024-05-13 15:07 UTC, redeboer commented on schema.json
> +        },
There is currently no example of a model with `ls`. What keys should a vertex of type `ls` define?

2024-05-14 12:31 UTC, redeboer commented on schema.json
> +          ],
Okay makes sense. 9069c7a also removes the implemenation

2024-05-14 12:34 UTC, redeboer commented on schema.json
> +        },
Let's say we want both vertices here to be `ls`

https://github.com/RUB-EP1/amplitude-serialization/blob/ecee71af8f77bc0360b3c5d8bc85592802652eb0/models/Lc2ppiK.json#L46-L60

What should it look like?

2024-05-14 12:38 UTC, redeboer commented on schema.json
> +        },
Ah nvm, got it from #34:

https://github.com/RUB-EP1/amplitude-serialization/blob/c15a1f49d73579a9209ce36ef8173e0dc2b46081/models/Lb2pKg.json#L46-L61

2024-05-14 13:51 UTC, redeboer commented on schema.json
> +        },
Currently this is a string because it is done like this in #34. @mmikhasenko, better to just make it `integer` with minimum 0? Same like in the channel definition for instance:
https://github.com/RUB-EP1/amplitude-serialization/blob/9004a871db1c596571c6f480b32e37035b463cfe/schema.json#L84-L88

2024-05-14 13:52 UTC, redeboer commented on schema.json
> +        },
See f3c78d1. You mean `l` is always required, but `s` is not?

2024-05-21 11:50 UTC, redeboer commented on schema.json
> +        },
> I think it's better to be supportive for both formats, I would not restrict to either

With 0e8b71c both are allowed.

2024-05-22 07:21 UTC, mmikhasenko commented
good moment to merge?

2024-05-22 07:23 UTC, redeboer commented
> good moment to merge?

Just needs a PR approval ;)

2024-05-22 07:38 UTC, IlyaSegal approved these changes
Very nice:-)

2024-05-26 06:05 UTC, redeboer commented
> Just needs a PR approval ;)

@mmikhasenko if you approve this PR, it should merge automatically

2024-05-27 20:32 UTC, mmikhasenko approved these changes

2024-05-27 21:48 UTC, merged