Lb2p kg
RUB-EP1/amplitude-serialization pull request #34
Opened 2024-05-14 11:57 UTC by IlyaSegal

Pull request for Lb2pKg with json and qmd files.

2024-05-14 12:25 UTC, redeboer requested changes
Super nice!
Seems that the model results in NaN values for now (?)

2024-05-14 12:25 UTC, redeboer commented on docs/_quarto.yml
> +          - julia/Lb2pKg.qmd
I would use lower caps for the file name. The URL of the corresponding web page is based on this file name and it is usual to have URLs lower case.

I'm fine with the JSON file being case sensitive.

2024-05-14 12:25 UTC, redeboer commented on docs/julia/Lb2pKg.qmd
> +#        m * quadgk(projection_integrand(I, masses(model), m^2; k), 0, 1)[1]
At some stage, CI will become super slow if each notebook integrates analytically. @mmikhasenko is it really needed?

2024-05-14 12:25 UTC, redeboer commented on docs/julia/Lb2pKg_files/execute-results/html.json
@IlyaSegal can you add `*.html` to `.gitignore` and remove this file?
Afaics, these files are generated in the source code folder (instead of `_build/html`) if you use `quarto render` (=`pixi run doc`).

2024-05-14 12:25 UTC, redeboer commented on docs/julia/Lb2pKg.qmd
> +c
We'll need to update this text with the fixes  of #28, once that is merged.

2024-05-14 12:39 UTC, mmikhasenko commented on docs/julia/Lb2pKg.qmd
> +#        m * quadgk(projection_integrand(I, masses(model), m^2; k), 0, 1)[1]
No, removing

2024-05-14 12:40 UTC, mmikhasenko commented on docs/julia/Lb2pKg.qmd
> +c
Removing for now

2024-05-14 13:06 UTC, mmikhasenko commented
I found the cause of the Inf: it was the normalization factors from #31

The BlattWeisskopf is currently defined as `zˆL / pol(z)` where `z = R*p`. If the radius is `0`, the factor is `0`. And `1/0` gives `Inf` resulting in `NaN`.

Now, the formfactors are replaced by the newly introduced `MomentumPower` factors.

2024-05-15 14:25 UTC, redeboer approved these changes
Beautiful!

2024-05-17 10:23 UTC, mmikhasenko commented
Shall we aim to merge it today?

AFAIR, the status is that the validation tests fail.
A suggestion to proceeded is to create more validations.

Here is an input from the "true" model implementation, what we need to proceed here (open Lb2pKpi notebook, evaluate, report number here):
 - [ ] all lineshapes evaluated at `sigma1`, or `sigma2`, or `sigma3`
 - [ ] All formfactors evaluated at `sigma1`, or `sigma2`, or `sigma3`

2024-05-17 16:50 UTC, IlyaSegal commented
After updating couplings, all validation points are yellow (difference in the third decimal digit).

2024-05-17 16:54 UTC, mmikhasenko commented
That was it, congratulations!
![image](https://github.com/RUB-EP1/amplitude-serialization/assets/22725744/e6c4c0d0-458f-4205-a804-336c89d63599)

2024-05-21 17:51 UTC, redeboer approved these changes
Nice, [preview](https://github.com/RUB-EP1/amplitude-serialization/actions/runs/9178763013?pr=34) looks good now!

![image](https://github.com/RUB-EP1/amplitude-serialization/assets/29308176/d4982f3b-9146-4a50-87cb-341fdb18e5b2)
![image](https://github.com/RUB-EP1/amplitude-serialization/assets/29308176/d8770187-e964-415f-b047-a8dc0375bb8f)
![image](https://github.com/RUB-EP1/amplitude-serialization/assets/29308176/d8794386-d23e-4339-98f7-cb70f7b8fbab)

2024-05-21 18:04 UTC, merged